### ISSUE TITLE
Footer Visibility in mobile view 

### ISSUE THREAD

**Issue by Anu277** [Saichandra2520/DSA-Checklist#22]
**Describe the bug**
Footer isn't completely visible in mobile.

**To Reproduce**
1. Go to Home page
2. Scroll down a little 
3. See error

**Expected behavior**
The footer can be positioned as static, but when it is, in desktop view, the footer will be directly below the main tag, which can be adjusted by responsive design conditions.

**Screenshots**
![WhatsApp Image 2024-09-07 at 14 59 07_b0d70e57](https://github.com/user-attachments/assets/b8328950-5b80-4060-b61f-4a187eb32067)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: v1.69.162

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7 pro
 - OS: Android 10
 - Browser: Chrome
 - Version: 127.0.6533.103

**Comment by maheshtamarakar** [comment]
for me its completely visible
![image](https://github.com/user-attachments/assets/96f01229-f7f8-49a0-8ddc-7e4ee7c7fe95)
can you help me reproduce it

**Comment by maheshtamarakar** [comment]
![image](https://github.com/user-attachments/assets/9b418113-35fb-4d83-bba5-0c7bcb3cf0bc)
here's the resolution i'm using

**Comment by Saichandra2520** [comment]
<img width="450" alt="Screenshot 2024-09-07 at 8 03 46 PM" src="https://github.com/user-attachments/assets/e80f0990-938e-46bd-9019-57ea25519301">

@maheshtamarakar 
The footer is not completely visible add some padding and make it look good. Thank you!!
