### ISSUE TITLE
Center the UI containers

### ISSUE THREAD

**Issue by Saichandra2520** [Saichandra2520/DSA-Checklist#25]
Need to fix the UI. I have multiple container, I want them to be centered

![Screenshot_2024-09-08-16-17-53-794-edit_com.android.chrome.jpg](https://github.com/user-attachments/assets/24aea6dc-8b11-48e3-8c83-b6ade04f0ec1)

**Comment by rameshkrishnan-s** [comment]
Does the div.'s are need to be centered for mobile view ??  @Saichandra2520

**Comment by Saichandra2520** [comment]
> Does the div.'s are need to be centered for mobile view ?? @Saichandra2520

Yes

**Comment by rameshkrishnan-s** [comment]
Can you assign this me??

**Comment by Saichandra2520** [comment]
@rameshkrishnan-s yes you can start your work. make it responsible as much as possible. I assigned you for this work.

**Comment by rameshkrishnan-s** [comment]
![image](https://github.com/user-attachments/assets/7e564b01-c4d5-4478-b45a-71e2bdaa89bd)
@Saichandra2520 Brother is this OK??

**Comment by Saichandra2520** [comment]
@rameshkrishnan-s yeah its fine. Did you check once this for responsive? Does your code make any issue with desktop version? if not you can go ahead with pull request.

**Comment by Saichandra2520** [comment]
@rameshkrishnan-s  Any progress?

**Comment by rameshkrishnan-s** [comment]
@Saichandra2520 will complete soon.
